Feature/book page
RSS-Team-Five/RSLang pull request #32
Opened 2022-08-20 10:48 UTC by YuliyaShu

#### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related trello card link

[_create book page_](https://trello.com/c/afIHWJuA)

#### 💡 Background and solution
Страница учебника содержит имя страницы, 6 основных категорий слов по сложности (каждая карточка будет вести на отдельную страницу категории, в процессе), седьмая категория изначально неактивная. становится активной, когда state.user.isAuthorized станет true. Не забыть связать активность седьмой карточки со статусом state.user.isAuthorized

2022-08-20 10:49 UTC, valerydluski commented on src/scss/pages/_bookPage.scss
> +}
![image](https://user-images.githubusercontent.com/57412523/185742595-87d47be4-9812-4e13-badd-05e8b33d8872.png)

2022-08-20 10:57 UTC, YuliyaShu commented on src/scss/pages/_bookPage.scss
> +}
Уже исправила

2022-08-20 11:09 UTC, Bumble-sakh requested changes

2022-08-20 11:09 UTC, Bumble-sakh commented on src/views/pages/bookPage.ts
> +];
может быть это тоже вынести в конфиг?
оно ведь нигде не меняется...

2022-08-20 11:09 UTC, Bumble-sakh commented on src/scss/abstracts/_isActive.scss
> +}
.inactive {
  opacity: 50%;
  
  &:hover {
    transform: none;
    box-shadow: none;
    transition: none;
    cursor: default;
  }
}

2022-08-20 11:11 UTC, Bumble-sakh commented on src/views/pages/bookPage.ts
> +];
может быть это тоже вынести в конфиг?
оно ведь нигде не меняется...

2022-08-20 11:20 UTC, YuliyaShu commented on src/views/pages/bookPage.ts
> +];
а ты какой конфиг имеешь ввиду? в ютилс куда-нибудь?

2022-08-20 11:20 UTC, YuliyaShu commented on src/scss/abstracts/_isActive.scss
> +}
Обновила

2022-08-20 18:32 UTC, valerydluski commented on src/views/pages/bookPage.ts
> +];
можно создать папку data и туда закинуть

2022-08-20 19:38 UTC, Bumble-sakh commented on src/views/pages/bookPage.ts
> +];
У нас же есть
https://github.com/RSS-Team-Five/RSLang/blob/dev/src/models/Config.ts

2022-08-21 10:59 UTC, YuliyaShu commented on src/views/pages/bookPage.ts
> +];
Перенесла https://github.com/RSS-Team-Five/RSLang/pull/32/commits/f9dd4adb547afdd05564e1ea4b87a63be34eb7d9

2022-08-21 11:13 UTC, valerydluski approved these changes

2022-08-21 14:47 UTC, Bumble-sakh approved these changes

2022-08-21 15:11 UTC, merged