Feat/new features on word cards
RSS-Team-Five/RSLang pull request #52
Opened 2022-08-25 09:10 UTC by YuliyaShu

#### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related trello card link

[_сложные слова_
](https://trello.com/c/BetCiwNy)
#### 💡 Background and solution

_Describe the big picture of your changes here_
Звездочкой можно отметить слово сложным и снять пометку. 
Когда слово отмечено сложным, добавляется слово юзера на сервер - сложность устанавливается 'hard'. Выделяется стилем и попадает на страницу сложных слов.
```
await state.user?.createUserWord(state.user.user, this.word.id, {
          difficulty: 'hard',
          optional: {},
        });
```

Когда убирается отметка сложности, слово удаляется из слов юзера на сервере, удаляется со страницы сложных слов. Меняется стиль на обычный.
` await state.user?.deleteUserWord(state.user?.user, this.word.id);`

2022-08-25 15:22 UTC, Bumble-sakh requested changes

2022-08-25 15:22 UTC, Bumble-sakh commented on src/views/pages/sectionPage.ts
>      } else if (group === config.BOOK.maxGroup && allUserWordsOnPage) {
не нужная проверка
выше проверяется, что секция 6 и длинна allUserWordsOnPage > 0

2022-08-25 15:22 UTC, Bumble-sakh commented on src/views/pages/sectionPage.ts
> +        const userWord = (await oneWordFromAPI(word.wordId)) as IWord;
Обращение к АПИ на прямую

2022-08-25 15:22 UTC, Bumble-sakh commented on src/views/components/WordCardClass.ts
> +      : new CustomElement('img', {
Тут проверяется есть ли слово в списке слов пользователя ,что б нарисовать правильную иконку, а 
дальше везде для этого проверяется путь внутри иконки?

2022-08-25 15:22 UTC, Bumble-sakh commented on src/views/components/WordCardClass.ts
> +  // }
не используемый код?

2022-08-25 15:24 UTC, Bumble-sakh reviewed
Обсуждение:
Может для иконок, вместо отдельных СВГ использовать иконочный шрифт?

2022-08-25 15:35 UTC, YuliyaShu commented on src/types/WordCard.ts
> +// }
да .я удалила файл. случайно подтянулся

2022-08-25 15:36 UTC, YuliyaShu commented on src/views/components/WordCardClass.ts
> +  userWords = state.user?.user.userWords;
ну в короткую переменную поместила. чтобы удобнее пользоваться было в классе

2022-08-25 15:38 UTC, YuliyaShu commented on src/views/components/WordCardClass.ts
> +  // }
это заготовка для нового функционала

2022-08-25 15:43 UTC, YuliyaShu commented on src/views/components/WordCardClass.ts
> +      : new CustomElement('img', {
да

2022-08-25 15:53 UTC, muannna commented on src/views/pages/sectionPage.ts
> +        const userWord = (await oneWordFromAPI(word.wordId)) as IWord;
Мы же можем тут обращаться к апи, потому что это слово не юзера, а из базы

2022-08-25 15:59 UTC, YuliyaShu commented on src/views/pages/sectionPage.ts
> +        const userWord = (await oneWordFromAPI(word.wordId)) as IWord;
Поправила

2022-08-25 16:00 UTC, YuliyaShu commented on src/views/pages/sectionPage.ts
>      } else if (group === config.BOOK.maxGroup && allUserWordsOnPage) {
group === config.BOOK.maxGroup эту проверку убрала
allUserWordsOnPage эта необходима для исключения в блоке ниже значения null

2022-08-25 16:02 UTC, YuliyaShu commented on src/views/pages/sectionPage.ts
> +        const userWord = (await oneWordFromAPI(word.wordId)) as IWord;
> Мы же можем тут обращаться к апи, потому что это слово не юзера, а из базы

У меня метод у класса слова есть .я на него здесь переписала 
const userWord = await new Word(word.wordId).getOneWord();

2022-08-26 10:01 UTC, muannna commented on src/views/pages/sectionPage.ts
> +        const userWord = (await oneWordFromAPI(word.wordId)) as IWord;
Ghsahjdgasjd

2022-08-27 21:46 UTC, YuliyaShu commented on src/views/components/WordCardClass.ts
> +      : new CustomElement('img', {
обновила логику

2022-08-28 00:39 UTC, YuliyaShu commented
Новый ПР https://github.com/RSS-Team-Five/RSLang/pull/55 включает все коммиты этого ПР

2022-08-28 00:39 UTC, closed without merging